spring:
  data:
    mongodb:
      #host: localhost:27017
      #database: viajes
      uri: mongodb://localhost:27017/viajes
server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
