spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hostMySql}:3306/viajes?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://${hostEureka}:8761/eureka
  instance:
    hostname: ${hostEureka}
